version: 2
updates:
  # Enable version updates for NuGet
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/tests/e2e"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5 